# Generated by Django 5.2 on 2025-05-07 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=9)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to='event.event')),
            ],
            options={
                'db_table': 'AYT_EXHIBITION',
            },
        ),
    ]
