# Generated by Django 5.2 on 2025-05-13 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_remove_event_check_datetime_order_and_more"),
        ("exhibition", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibition",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exhibitions",
                to="event.event",
            ),
        ),
    ]
