# Generated by Django 5.2 on 2025-05-13 05:03

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibition", "0005_alter_exhibition_end_date_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibition",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exhibition",
            name="users",
            field=models.ManyToManyField(
                related_name="exhibition", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="end_date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 23, 1, 3, 33, 688356)
            ),
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="start_date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 13, 1, 3, 33, 688319)
            ),
        ),
    ]
