# Generated by Django 5.2 on 2025-05-13 17:54

import datetime
import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0007_alter_exhibition_end_date_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 23, 13, 54, 53, 238663)),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='expenses',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 13, 54, 53, 238631)),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='exhibition', to=settings.AUTH_USER_MODEL),
        ),
    ]
