services:
  backend:
    build:
      context: ./be/server/
      dockerfile: ./Dockerfile
    env_file: "./be/server/.env"
    command: python manage.py runserver 0.0.0.0:80
    environment:
      DB_HOST: "host.docker.internal"
    ports:
      - "8000:80"
      - "5432:5432"
    extra_hosts:
        - "host.docker.internal:host-gateway"
