# Generated by Django 5.2 on 2025-05-13 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seminar", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seminar",
            name="event",
        ),
        migrations.RemoveField(
            model_name="seminar",
            name="id",
        ),
        migrations.AddField(
            model_name="seminar",
            name="end_date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 23, 0, 15, 5, 126264)
            ),
        ),
        migrations.AddField(
            model_name="seminar",
            name="event_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="seminar",
            name="event_name",
            field=models.CharField(db_index=True, default="Test", max_length=100),
        ),
        migrations.AddField(
            model_name="seminar",
            name="event_topic",
            field=models.CharField(
                choices=[
                    ("LIT", "Literature & Author Talks"),
                    ("HIS", "History & Archives"),
                    ("SCI", "Science & Nature"),
                    ("ART", "Art Exhibitions & Workshops"),
                    ("MUS", "Music & Performance"),
                    ("TEC", "Technology & Innovation"),
                    ("EDU", "Education & Learning Skills"),
                    ("WRIT", "Creative Writing"),
                    ("CHD", "Children’s Programs"),
                    ("YTH", "Youth & Teen Engagement"),
                    ("CUL", "Cultural Heritage"),
                    ("COM", "Community & Social Issues"),
                    ("ENV", "Environment & Sustainability"),
                    ("HLTH", "Health & Wellness"),
                    ("DIG", "Digital Literacy"),
                    ("FILM", "Film Screenings & Analysis"),
                    ("PHI", "Philosophy & Ethics"),
                    ("BIZ", "Business & Career Development"),
                    ("DIY", "DIY, Crafts & Makerspaces"),
                    ("LANG", "Language & Literacy"),
                ],
                default="LIT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="seminar",
            name="start_date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 13, 0, 15, 5, 126226)
            ),
        ),
        migrations.AddField(
            model_name="seminar",
            name="topic_bitmap",
            field=models.BigIntegerField(default=0),
        ),
    ]
