# Generated by Django 5.2 on 2025-05-13 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0007_alter_seminar_end_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 23, 13, 57, 43, 405608)),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 13, 57, 43, 405575)),
        ),
    ]
