# Generated by Django 5.2 on 2025-05-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('event_topic', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'AYT_EVENT',
            },
        ),
    ]
