# Generated by Django 5.2 on 2025-05-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='topic_bitmap',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_date_time__gt', models.F('start_date_time'))), name='check_datetime_order'),
        ),
    ]
