# Generated by Django 5.2 on 2025-05-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_check_datetime_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='check_datetime_order',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_date_time__gt', models.F('start_date_time'))), name='check_datetime_order'),
        ),
    ]
