import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from '@/context/AuthContext';

import Header from '@/components/header';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthProvider>
            <html lang="en">
                <body
                    className={`
                        ${geistSans.variable} ${geistMono.variable} antialiased
                        bg-fixed bg-center bg-no-repeat bg-cover
                        min-h-screen
                        `}
                    style={{
                        backgroundImage: "url('/global_background.jpg')",
                    }}>
                    <div className="absolute inset-0 bg-gradient-to-b from-black/60 to-transparent z-0" />
                    {/* Content */}
                    <div className="relative z-10">
                        <Header />
                        <Toaster position="bottom-center" />
                        {children}
                    </div>
                </body>
            </html>

        </AuthProvider>
    );
}
