# Generated by Django 5.2 on 2025-05-07 00:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
