# Generated by Django 5.2 on 2025-05-09 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.rental')),
            ],
            options={
                'db_table': 'AYT_INVOICE',
            },
        ),
    ]
