# Generated by Django 5.2 on 2025-05-09 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('rental_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='rental',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental_system.rental'),
        ),
    ]
