# Generated by Django 5.2 on 2025-05-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
