# Generated by Django 5.2 on 2025-05-09 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('sponser_id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'AYT_SPONSER',
            },
        ),
        migrations.CreateModel(
            name='SponserSeminarRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.seminar')),
                ('sponser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponser.sponser')),
            ],
            options={
                'db_table': 'AYT_SPONSER_SEMINAR_RELATIONSHIP',
            },
        ),
    ]
