# Generated by Django 5.2 on 2025-05-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='sponser_id',
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
