# Generated by Django 5.2 on 2025-05-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponser", "0003_sponser_sponsor_type_alter_sponser_lname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponser",
            name="email",
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
