# Generated by Django 5.2 on 2025-05-07 01:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_id",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("descr", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "AYT_ROOM",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_of_people",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("description", models.TextField(max_length=100)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="room.room"
                    ),
                ),
            ],
            options={
                "db_table": "AYT_BOOKING",
                "ordering": ["start_datetime"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_datetime__gt", models.F("start_datetime"))
                        ),
                        name="check_start_datetime",
                    )
                ],
            },
        ),
    ]
