# Generated by Django 5.2 on 2025-05-07 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["room", "start_datetime"]},
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("room", "start_datetime")},
        ),
    ]
