# Generated by Django 5.2 on 2025-05-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0002_alter_booking_options_alter_booking_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image_url",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
