# Generated by Django 5.2 on 2025-04-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('auth_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('mname', models.CharField(blank=True, max_length=10, null=True)),
                ('lname', models.CharField(blank=True, max_length=30, null=True)),
                ('addr_st', models.CharField(blank=True, max_length=100, null=True)),
                ('addr_city', models.CharField(blank=True, max_length=100, null=True)),
                ('addr_state', models.CharField(blank=True, max_length=100, null=True)),
                ('addr_ctry', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'AYT_AUTHOR',
            },
        ),
    ]
