# Generated by Django 5.2 on 2025-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_authorbookrelationship_authorseminarrelationship'),
        ('book', '0006_alter_book_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorbookrelationship',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='authorbookrelationship',
            unique_together={('author', 'book')},
        ),
    ]
