# Generated by Django 5.2 on 2025-05-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_authorbookrelationship_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
