# Generated by Django 5.2 on 2025-04-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'AYT_BOOK',
            },
        ),
    ]
