# Generated by Django 5.2 on 2025-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_book_cover_url_book_summary_alter_book_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pub_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="topic",
            field=models.CharField(
                choices=[
                    ("FIC", "Fiction"),
                    ("NON", "Non-Fiction"),
                    ("SCI", "Science"),
                    ("HIS", "History"),
                    ("TECH", "Technology"),
                    ("PHI", "Philosophy"),
                    ("ART", "Art"),
                    ("MUS", "Music"),
                    ("BIO", "Biography"),
                    ("SH", "Self-Help"),
                    ("BUS", "Business"),
                    ("REL", "Religion"),
                    ("HEA", "Health"),
                    ("EDU", "Education"),
                    ("TRV", "Travel"),
                    ("CKG", "Cooking"),
                    ("SPT", "Sports"),
                    ("POE", "Poetry"),
                    ("COM", "Comics"),
                    ("CHD", "Children"),
                ],
                default="FIC",
                max_length=50,
            ),
        ),
    ]
