# Generated by Django 5.2 on 2025-05-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_alter_book_pub_date_alter_book_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pub_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
