# Generated by Django 5.2 on 2025-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_authorbookrelationship_role_and_more'),
        ('book', '0006_alter_book_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='book', through='author.AuthorBookRelationship', to='author.author'),
        ),
    ]
