# Generated by Django 5.2 on 2025-05-08 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book", "0004_alter_book_pub_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                ("copy_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("on_loan", "On Loan"),
                            ("reserved", "Reserved"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="book.book",
                    ),
                ),
            ],
        ),
    ]
