# Generated by Django 5.2 on 2025-05-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_copy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookcopy',
            table='AYT_BOOK_COPY',
        ),
    ]
